# coding: utf-8

"""
    Buycycle

    DevOps homework  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_api import ApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.api_api.ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_account(self):
        """Test case for add_account

        Add a new account to the store  # noqa: E501
        """
        pass

    def test_add_deal(self):
        """Test case for add_deal

        Add a new deal to the store  # noqa: E501
        """
        pass

    def test_add_person(self):
        """Test case for add_person

        Add a new person to the store  # noqa: E501
        """
        pass

    def test_add_transfer(self):
        """Test case for add_transfer

        Add a new transfer to the store  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        Finds Accounts by accountId  # noqa: E501
        """
        pass

    def test_get_deals(self):
        """Test case for get_deals

        Finds deals by accountId  # noqa: E501
        """
        pass

    def test_get_debts(self):
        """Test case for get_debts

        Finds debts by accountId  # noqa: E501
        """
        pass

    def test_get_persons(self):
        """Test case for get_persons

        Finds Persons by accountId  # noqa: E501
        """
        pass

    def test_get_transfers(self):
        """Test case for get_transfers

        Finds Transfers by accountId  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
