# coding: utf-8

"""
    Buycycle

    DevOps homework  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transfer import Transfer  # noqa: E501
from swagger_client.rest import ApiException


class TestTransfer(unittest.TestCase):
    """Transfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransfer(self):
        """Test Transfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transfer.Transfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
