# coding: utf-8

"""
    Buycycle

    DevOps homework  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.debt import Debt  # noqa: E501
from swagger_client.rest import ApiException


class TestDebt(unittest.TestCase):
    """Debt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDebt(self):
        """Test Debt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.debt.Debt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
