# coding: utf-8

"""
    Buycycle

    DevOps homework  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.person_debtors import PersonDebtors  # noqa: E501
from swagger_client.rest import ApiException


class TestPersonDebtors(unittest.TestCase):
    """PersonDebtors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonDebtors(self):
        """Test PersonDebtors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.person_debtors.PersonDebtors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
